### ISSUE TITLE
NOT WORK MINT 18

### ISSUE THREAD

**Issue by iksws** [linuxmint/nemo-extensions#168]
I use nemo and rabbits not show more in menu and folders :(

**Comment by iksws** [comment]
more details
(nemo:23398): Gtk-WARNING **: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client
sys:1: PyGIWarning: Nemo was imported without specifying a version first. Use gi.require_version('Nemo', '3.0') before import to ensure that the right version gets loaded.
  File "/usr/share/nemo-python/extensions/RabbitVCS.py", line 655
    return NemoContextMenu(self.structure, self.conditions, self.callbacks).menu

**Comment by EduardDopler** [comment]
RabbitVCS is just crappy software. _Stop using it._
It uses old, buggy and deprecated tools, is bloated, doesn't receive (proper) fixes, if any, is broken by design, is hardly to maintain working, and so on. There are tons of good, dedicated software for your purpose, like gitg or [GitKraken](https://www.gitkraken.com/features), to name only two if you really need a GUI.

**Comment by GLolol** [comment]
Seconded, and it looks like RabbitVCS is capable of causing some pretty bad data loss: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=817231

**Comment by iksws** [comment]
@EduardDopler 
Thks for tell me others options, I dont know others programs!
