### ISSUE TITLE
update meld breaks nemo-compare

### ISSUE THREAD

**Issue by gbuntu127** [linuxmint/nemo-extensions#173]
I built and installed the latest meld (3.16.2) from [here](http://meldmerge.org/), now the nemo compare function does not work any more, please let me know if there is any way I can get it work again. Thanks.

I have downloaded source of meld 3.16.2 and installed it by:
`sudo python setup.py install`

Here are some related information: 

```
$ inxi -S
      System:    Kernel: 4.4.0-31-generic x86_64 (64 bit) Desktop: Cinnamon 3.0.7
      Distro: Linux Mint 18 Sarah
```

**Comment by gbuntu127** [comment]
I solved the problem by install meld with usr prefix:

`python setup.py install --prefix=/usr`

Please close the issue.

**Comment by EduardDopler** [comment]
Please close the issue yourself.

By the way, the current `nemo-comare` implementation searches known engines in `/usr/bin` and `/usr/local/bin`. Though the code of it is terrible, so maybe deleted diff engines aren't removed properly. I guess that python's setuptools installed your new meld version with the prefix `/usr/local` hence it should have been found—so it might be just a broken `NemoCompareConfig` which should reload itself when you delete its config file, start its preferences (`nemo-compare-preferences`) and restart nemo (`nemo -q`) afterwards. Crappy, I know, this is only fixed in the Python 3 version I developed (by rewritting the complete logic).
