### ISSUE TITLE
Dependencies in Ubuntu Desktop 18.04 LTS

### ISSUE THREAD

**Issue by TogarUshindi** [linuxmint/nemo-extensions#339]
Two questions:

1) Is it "python-nemo" or "nemo-python"?
2) How do I install a version newer or equal to 3.9.0?

When I attempt to `$ sudo dpkg -i nemo-audio-tab_4.2.0_all.deb` it comes up with:

```
The following packages have unmet dependencies:
 nemo-audio-tab : Depends: python-nemo (>= 3.9.0)
```
I already have Nemo installed via Gnome / Snap, but I try anyways:
```
$ sudo apt install python-nemo
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'nemo-python' instead of 'python-nemo'
nemo-python is already the newest version (3.6.0-1).
```
So, that's where my two questions come from. Is it `python-nemo` or `nemo-python`? And how do I obtain and install the newest version via cli? (and will that conflict with the snap version?)

**Comment by okaestne** [comment]
1. `nemo-python` is the old name for the python bindings for Nemo. So `python-nemo` is the correct one.
2. If you are using Linux Mint, you can install the plugin with `apt install nemo-audio-tab`. Just need to activate the plugin in Nemo (Menu: Edit > Plugins)

**Comment by xenopeek** [comment]
python-nemo is the correct name but Debian packagers and thus Ubuntu renamed it to nemo-python because "it's a Python extension for Nemo, not a Nemo extension for Python"—despite existence of packages python-nautilus and python-caja in Debian which serve the exact same purpose for those file managers and aren't renamed. When using Linux Mint or LMDE, the package name is correctly python-nemo.

When installing a newer Nemo version or Nemo extensions on Debian or Ubuntu make sure to upgrade **_all_** installed Nemo packages or you may run in to this.
